#ifndef PGB_CPU_PRIVATE_ISA_CONSTANTS_H
#define PGB_CPU_PRIVATE_ISA_CONSTANTS_H

#define LR35902_OPCODE_TABLE_SIZE							256
#define LR35902_PREFIX_CB_OPCODE_TABLE_SIZE						256

#endif /* PGB_CPU_PRIVATE_ISA_CONSTANTS_H */
