#ifndef PGB_DEVICE_PRIVATE_REGISTERS_INTERRUPT_REGS_H
#define PGB_DEVICE_PRIVATE_REGISTERS_INTERRUPT_REGS_H

#define DMG_INTERRUPT_REGISTER_IF                                 0xff0f:0xff0f /* RW */
#define DMG_INTERRUPT_REGISTER_IF_V_BLANK_INTERRUPT                         0:0
#define DMG_INTERRUPT_REGISTER_IF_V_BLANK_INTERRUPT_REQUEST                   1
#define DMG_INTERRUPT_REGISTER_IF_LCD_STAT_INTERRUPT                        1:1
#define DMG_INTERRUPT_REGISTER_IF_LCD_STAT_INTERRUPT_REQUEST                  1
#define DMG_INTERRUPT_REGISTER_IF_TIMER_INTERRUPT                           2:2
#define DMG_INTERRUPT_REGISTER_IF_TIMER_INTERRUPT_REQUEST                     1
#define DMG_INTERRUPT_REGISTER_IF_SERIAL_INTERRUPT                          3:3
#define DMG_INTERRUPT_REGISTER_IF_SERIAL_INTERRUPT_REQUEST                    1
#define DMG_INTERRUPT_REGISTER_IF_JOYPAD_INTERRUPT                          4:4
#define DMG_INTERRUPT_REGISTER_IF_JOYPAD_INTERRUPT_REQUEST                    1
#define DMG_INTERRUPT_REGISTER_IE                                 0xffff:0xffff /* RW */
#define DMG_INTERRUPT_REGISTER_IE_V_BLANK_INTERRUPT                         0:0
#define DMG_INTERRUPT_REGISTER_IE_V_BLANK_INTERRUPT_DISABLE                   0
#define DMG_INTERRUPT_REGISTER_IE_V_BLANK_INTERRUPT_ENABLE                    1
#define DMG_INTERRUPT_REGISTER_IE_LCD_STAT_INTERRUPT                        1:1
#define DMG_INTERRUPT_REGISTER_IE_LCD_STAT_INTERRUPT_DISABLE                  0
#define DMG_INTERRUPT_REGISTER_IE_LCD_STAT_INTERRUPT_ENABLE                   1
#define DMG_INTERRUPT_REGISTER_IE_TIMER_INTERRUPT                           2:2
#define DMG_INTERRUPT_REGISTER_IE_TIMER_INTERRUPT_DISABLE                     0
#define DMG_INTERRUPT_REGISTER_IE_TIMER_INTERRUPT_ENABLE                      1
#define DMG_INTERRUPT_REGISTER_IE_SERIAL_INTERRUPT                          3:3
#define DMG_INTERRUPT_REGISTER_IE_SERIAL_INTERRUPT_DISABLE                    0
#define DMG_INTERRUPT_REGISTER_IE_SERIAL_INTERRUPT_ENABLE                     1
#define DMG_INTERRUPT_REGISTER_IE_JOYPAD_INTERRUPT                          4:4
#define DMG_INTERRUPT_REGISTER_IE_JOYPAD_INTERRUPT_DISABLE                    0
#define DMG_INTERRUPT_REGISTER_IE_JOYPAD_INTERRUPT_ENABLE                     1

#endif /* PGB_DEVICE_PRIVATE_REGISTERS_INTERRUPT_REGS_H */
