#ifndef PGB_DEVICE_PRIVATE_REGISTERS_JOYPAD_REGS_H
#define PGB_DEVICE_PRIVATE_REGISTERS_JOYPAD_REGS_H

#define DMG_JOYPAD_P1_JOYP                                        0xff00:0xff00
#define DMG_JOYPAD_P1_JOYP_P15_SELECT_BUTTON_KEYS                           5:5
#define DMG_JOYPAD_P1_JOYP_P15_SELECT_BUTTON_KEYS_SELECT                      0
#define DMG_JOYPAD_P1_JOYP_P14_SELECT_DIRECTION_KEYS                        4:4
#define DMG_JOYPAD_P1_JOYP_P14_SELECT_DIRECTION_KEYS_SELECT                   0
#define DMG_JOYPAD_P1_JOYP_P13_INPUT_DOWN_OR_START                          3:3
#define DMG_JOYPAD_P1_JOYP_P13_INPUT_DOWN_OR_START_PRESSED                    0
#define DMG_JOYPAD_P1_JOYP_P12_INPUT_UP_OR_SELECT                           2:2
#define DMG_JOYPAD_P1_JOYP_P12_INPUT_UP_OR_SELECT_PRESSED                     0
#define DMG_JOYPAD_P1_JOYP_P11_INPUT_LEFT_OR_BUTTON_B                       1:1
#define DMG_JOYPAD_P1_JOYP_P11_INPUT_LEFT_OR_BUTTON_B_PRESSED                 0
#define DMG_JOYPAD_P1_JOYP_P10_INPUT_RIGHT_OR_BUTTON_A                      0:0
#define DMG_JOYPAD_P1_JOYP_P10_INPUT_RIGHT_OR_BUTTON_A_PRESSED                0

#endif /* PGB_DEVICE_PRIVATE_REGISTERS_JOYPAD_REGS_H */
